object Form1: TForm1
  Left = 400
  Top = 250
  BiDiMode = bdLeftToRight
  Caption = 'Form1'
  ClientHeight = 200
  ClientWidth = 350
  Color = clBtnFace
  TransparentColorValue = clRed
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  ParentBiDiMode = False
  Position = poDesigned
  PixelsPerInch = 96
  TextHeight = 13
end
